import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: "100%",
    height: "50%",
  },
  label: {
    textAlign: "center",
    marginVertical: 5,
    fontSize: 18,
  },
  flatListContainer: {
    paddingBottom: 20,
    paddingTop: 10,
  },
  card: {
    flexDirection: "row",
    alignItems: "stretch",
    marginHorizontal: 16,
    marginVertical: 8,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    overflow: "hidden",
  },
  cardImageContainer: {
    position: "relative",
    width: 80,
    height: 80,
    margin: 12,
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: "#f0f0f0",
  },
  imageOverlay: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  imageLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  cardContent: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 16,
    justifyContent: "space-between",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  cardDetails: {
    gap: 4,
  },
  shopName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
    flex: 1,
    marginRight: 8,
  },
  oatMilkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  distanceText: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  upCharge: {
    fontSize: 15,
    fontWeight: "600",
    color: "#666",
    textAlign: "right",
    marginLeft: 10,
  },
  upchargeContainer: {
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#e9ecef",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  upChargeWithEmoji: {
    fontSize: 15,
    fontWeight: "600",
    textAlign: "right",
    marginLeft: 10,
    // Color will be dynamically set based on price
  },
  oatMilk: {
    fontSize: 14,
    color: "#4CAF50",
    fontWeight: "600",
    flex: 1,
  },
  locationButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#333",
    padding: 10,
    borderRadius: 8,
    zIndex: 1,
  },
  authContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: "#fff",
  },
  authLogo: {
    width: 120,
    height: 120,
    marginBottom: 20,
    resizeMode: "contain",
  },
  authTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
  },
  authSubtitle: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
  },
  input: {
    width: "100%",
    height: 44,
    paddingHorizontal: 12,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: "#f9f9f9",
  },
  authButton: {
    width: "100%",
    backgroundColor: "#4285F4",
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: "center",
  },
  authButtonSecondary: {
    width: "100%",
    backgroundColor: "#999",
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: "center",
  },
  authButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  logoutButton: {
    backgroundColor: "#cc0000",
    paddingVertical: 10,
    margin: 15,
    borderRadius: 6,
    alignItems: "center",
  },
  logoutButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  selectedShopOverlay: {
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 10,
    backgroundColor: "white",
    padding: 15,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },

  dismissButton: {
    marginTop: 10,
    alignSelf: "flex-end",
  },

  dismissText: {
    color: "#007AFF",
    fontWeight: "600",
  },

  // Hamburger Menu Styles
  hamburgerButton: {
    position: "absolute",
    top: 50,
    left: 20,
    backgroundColor: "#333",
    padding: 12,
    borderRadius: 8,
    zIndex: 1000,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  menuContainer: {
    backgroundColor: "white",
    marginTop: 100,
    marginLeft: 20,
    borderRadius: 12,
    paddingVertical: 8,
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  menuIcon: {
    marginRight: 15,
    width: 20,
  },
  menuText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },

  // Submit Shop Upcharge Styles
  upchargeContainer: {
    marginBottom: 10,
  },
  freeButton: {
    backgroundColor: "#f0f0f0",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginBottom: 15,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  freeButtonActive: {
    backgroundColor: "#e8f5e8",
    borderColor: "#4CAF50",
  },
  freeButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
  },
  freeButtonTextActive: {
    color: "#4CAF50",
  },
  priceInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 44,
  },
  dollarSign: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4285F4",
    marginRight: 5,
  },
  priceInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
    paddingVertical: 0,
  },
  whimsicalText: {
    fontSize: 14,
    color: "#666",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 8,
    paddingHorizontal: 10,
    lineHeight: 18,
  },

  // Upcharge emoji styles
  upchargeEmojiText: {
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 0.3,
  },
  overlayUpchargeEmoji: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 5,
  },
});
